on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Run checks
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn
        name: 'Install dependencies'
      - run: yarn format:check
        name: 'Check formatting'
